name: frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0  
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.1
  firebase_core: ^2.16.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^17.1.2
  flutter_svg: ^2.0.10
  flutter_staggered_animations: ^1.1.0
  geocoding: ^4.0.0
  cached_network_image: ^3.2.3
  flutter_countdown_timer: ^4.1.0
  url_launcher: ^6.1.11
  table_calendar: ^3.0.9
  flutter_rating_bar: ^4.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/profile.jpg
    - images/image.png
    - images/icons/plumber.png
    - images/icons/electrecian.png
    - images/icons/carpenter.png
    - images/icons/painter.png
    - images/icons/gardener.png
    - images/icons/cleaner.png
    - images/icons/car_repair.png
    - images/icons/hairdresser.png
    - images/app_logo.png   # 👈 your app logo

#  Launcher Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: images/app_logo.png
  min_sdk_android: 21
  remove_alpha_ios: true